--- Makefile	Mon Mar 17 22:36:14 2008
+++ Makefile.new	Fri Apr 18 22:06:34 2008
@@ -1,5 +1,7 @@
 TARGETS= Gen/float/libbox2d.a Gen/fixed/libbox2d.a
 
+include Makefile.python
+
 ifdef DEVKITPRO
 TARGETS += Gen/nds-float/lib/libbox2d.a Gen/nds-fixed/lib/libbox2d.a
 endif
